blank_issues_enabled: false
contact_links:
  - name: 🐛 Bug Report
    url: https://xenanetworks.com/support/bug-report/
    about: Create a report to help us improve XOA Chimera Core.
  - name: ✨ Feature Request
    url: https://xenanetworks.com/support/feature-request/
    about: Suggest an idea for XOA Chimera Core.
  - name: 🧐 Question
    url: https://xenanetworks.com/support/question/
    about: Ask us a question about XOA Chimera Core.
  - name: 📝 Check XOA Chimera Core Documentation
    url: https://docs.xenanetworks.com/projects/xoa-chimera-core
    about: The answer you are looking for may be in here.
  